### ISSUE TITLE
While Training getting need to set shuffle=True in StratifiedKFold()

### ISSUE THREAD

**Issue by bhadreshpsavani** [drc10723/toxic_comments_multilabel_classification#1]
Issue:

```
Traceback (most recent call last):
  File "train_model.py", line 129, in <module>
    prepare_and_train(train_iteration, (preprocess_para, training_para, model_para))
  File "train_model.py", line 78, in prepare_and_train
    train_val_split = custom_multi_label_skfold(data_dict['train_labels'],
  File "/media/data1/bhadresh/toxic_comments_multilabel_classification/toxic_model/utils.py", line 81, in custom_multi_label_skfold
    skf = StratifiedKFold(n_splits=n_folds, random_state=random_state)
  File "/toxic-classi/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/toxic-classi/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 636, in __init__
    super().__init__(n_splits=n_splits, shuffle=shuffle,
  File "/toxic-classi/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/toxic-classi/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 290, in __init__
    raise ValueError(
ValueError: Setting a random_state has no effect since shuffle is False. You should leave random_state to its default (None), or set shuffle=True.
```

**Comment by drc10723** [comment]
Merged fix MR
